title = "Get Scoped Artifacts"

description ="""
  Recipe that gets scoped artifacts (classes) and verifies them in a task.
  """

[agpVersion]
min = "8.0.0"

# Relevant Gradle tasks to run per recipe
[gradleTasks]
tasks = [
    "checkDebugClasses"
]

# All the relevant metadata fields to create an index based on language/API/etc'
[indexMetadata]
index = [
    "onVariant",
    "variant.artifacts.forScope",
    "ScopedArtifacts.Scope.ALL",
    "ScopedArtifacts.Scope.PROJECT",
    "ScopedArtifact.CLASSES",
]
